"use strict";
let avenger = 123;
let exist;
let power;
avenger = 'Dr. Strange';
console.log(avenger.charAt(0));
avenger = 150.5555;
console.log(avenger.toFixed(2));
console.log(exist);
console.log(power);
console.log("hola");
